### ISSUE TITLE
Latest version crashes game on start

### ISSUE THREAD

**Issue by NealSavage** [JamCoreModding/Jamtastic#19] opened 2022-04-21 17:43 UTC
Jamtastic 1.3.3 is crashing my game on start up. I am on fabric 1.18.2 
Here is logs.
https://pastebin.com/jPaYAq6R

**Comment by Jamalam360** [comment] 2022-04-21 17:52
I don't think that issue is due to jamtastic

**Comment by Jamalam360** [comment] 2022-04-21 17:52
I see com.aqupd.caracal.CaracalMain.onInitialize

Caracal is in the stacktrace

**Comment by NealSavage** [comment] 2022-04-21 17:54
Game launches if I delete the mod and if I  reinstall 1.3.2, launches fine , delete that and reinstall 1.3.3, crashes again. If it is conflicting with something else, it's due to something changed between 1.3.2 and 1.3.3. 
What's the solution in your opinion?

**Comment by Jamalam360** [comment] 2022-04-21 17:58
I'll have a proper look once I'm back at my computer

**Comment by Jamalam360** [comment] 2022-04-21 18:40
Are you sure that's the correct log file?

**Comment by NealSavage** [comment] 2022-04-21 18:41
Yes, but I'll do it again, one moment.

**Comment by NealSavage** [comment] 2022-04-21 18:46
https://pastebin.com/8xBVykFJ

**Comment by Jamalam360** [comment] 2022-04-21 18:55
I'm not sure what's going on here. I've shown the logs to a couple other modders and they both agree that there is no crash taking place in this log file. Not sure whether it's the wrong log or something worse is happening. Anymore context you may have would be great if possible

**Comment by NealSavage** [comment] 2022-04-21 18:57
I can send the MultiMC console output thing? 


https://pastebin.com/LLvcMkSv

**Comment by Jamalam360** [comment] 2022-04-21 19:00
Yep, thanks. that one actually has the crash log. I'm not sure what was wrong with the others but it looks like the crashlog had been cut off the end. I'll see what the issue is now

**Comment by Jamalam360** [comment] 2022-04-21 19:20
Yep, stupid mistake on my part. Should be fixed tonight if I manage to push the release by then

Thanks for reporting

**Closed** 2022-04-21 19:20 UTC
Labels: bug, information needed, code, priority: high

**Comment by NealSavage** [comment] 2022-04-21 19:21
Oh, yay! Thanks for the help! Glad my reporting helped out the mod in some small way. :)

**Comment by Jamalam360** [comment] 2022-04-22 18:32
1.3.4 should fix this
